// AUTO-GENERATED by scripts/generate-image-variants.mjs — do not hand-edit.
// Lists every photo "base" name actually present under public/images/ (i.e.
// every source .jpg this script found and generated variants for).
// `pz-photo-pending` (design.md D9) imports this array to decide
// placeholder-vs-real-photo purely from what's on disk.

export const AVAILABLE_PHOTO_BASES: readonly string[] = [
  'antes-despues-esparto-1',
  'antes-despues-esparto-2',
  'antes-despues-esparto-3',
  'antes-despues-espliego-1',
  'antes-despues-espliego-2',
  'antes-despues-espliego-3',
  'antes-despues-olivo-1',
  'antes-despues-olivo-2',
  'antes-despues-olivo-3',
  'antes-despues-romero-1',
  'antes-despues-romero-2',
  'antes-despues-romero-3',
  'antes-despues-vid-1',
  'antes-despues-vid-2',
  'antes-despues-vid-3',
  'atmosfera-esparto',
  'atmosfera-espliego',
  'atmosfera-olivo',
  'atmosfera-romero',
  'atmosfera-vid',
  'manos-pigmento',
  'resultado-esparto',
  'resultado-espliego',
  'resultado-olivo',
  'resultado-romero',
  'resultado-vid',
  'retrato-virginia',
  'salon-interior-1',
  'textura-lino',
];
