// AUTO-GENERATED by scripts/generate-image-variants.mjs — do not hand-edit.
// Lists every photo "base" name actually present under public/images/ (i.e.
// every source .jpg this script found and generated variants for).
// `pz-photo-pending` (design.md D9) imports this array to decide
// placeholder-vs-real-photo purely from what's on disk.

export const AVAILABLE_PHOTO_BASES: readonly string[] = [
  'atmosfera-esparto',
  'atmosfera-espliego',
  'atmosfera-olivo',
  'atmosfera-romero',
  'atmosfera-vid',
  'manos-pigmento',
  'retrato-virginia',
  'textura-lino',
];
